server:
  port: 4000
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    host: https://smssend.shumaidata.com
    path: /sms/send
    method: POST
    app-code: 4785a45c90d844efbcd93bd86ada3926
    templateId: M09DD535F4    # templateId
